### ISSUE TITLE
支持复制博文 id

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#102]
### ui上的哪部分与此新功能有关?

侧边栏控制台随笔列表右键上下文菜单

### 新功能描述

有时候，想要在博文中引用另一个已发布的博文，这时候，我通常是找到该博文，然后复制 hover 信息中的 <博文id>.html，然后在博文中用`[](../p/<博文id>.html)`引用：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/214048737-ee5ffd9a-5ed3-4f52-a4ad-8c8b8b353beb.png)

![image](https://user-images.githubusercontent.com/51501079/214049166-99556fcd-93d8-4b40-90c4-fd1130ebb258.png)

</details>

但这样不太方便。或许可提供一个方便博文引用的功能。

### [选填]建议的解决方案

可以提供一个“复制博文链接”的命令，运行命令，在面板中列出所有博文，选择对应博文后，写入 `[title](../p/id.html)` 到剪切板。

或者在博文的右键菜单中，添加一个“复制博文链接”的选项。

我按第二种思路，在 package.json 中加了：

```json
{
    "command": "vscode-cnb.copy-post-link",
    "title": "复制博文链接",
    "category": "Cnblogs Posts List",
    "enablement": "vscode-cnb.isAuthorized"
},
```

然后写了一个函数：

```
// copy-post-id.ts
import { Post } from "@/models/post";
import { env } from "vscode";

export const copyPostLink = (input: Post) => {
    const id = input?.id?.toString();
    const title = input?.title?.toString();
    if (id && title) {
        env.clipboard.writeText(`[${title}](../p/${id}.html)`);
    }
};
```

注册命令后准备测试，但获取博文失败（出现 404 错误）。或许可以参考一下。

**Comment by laggage** [comment]
[v1.6.2](https://github.com/cnblogs/vscode-cnb/tree/v1.6.2#%E5%A4%8D%E5%88%B6%E5%8D%9A%E6%96%87%E9%93%BE%E6%8E%A5)中支持了
