### ISSUE TITLE
本地图片路径被编码时提取失败

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#106]
**问题描述**

待提取的本地图片的路径中，某些字符可能被编码，比如空格被编码为 `%20`，这时候 [fs.existsSync](https://github.com/cnblogs/vscode-cnb/blob/1943868900c60446823e36ab691ed8906c42b078/src/services/images-extractor.service.ts#L125) 找不到文件。

**复现问题**

复现问题的步骤:
1. 在根文件夹（比如 test）中创建 test.md
2. 在 test 下创建 `JS 数组` 文件夹
3. 在 `JS 数组` 文件夹中加入一张图片（比如 test.jpg）
4. 在 test.md 中加入 `![](./JS%20数组/test.jpg)`（空格被编码）
5. 尝试上传到博客园（开启了图片提取）

**期望的结果**

图片提取成功。

**问题截图**

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/219022602-462a3384-b2c9-480e-af54-4c1a6872337a.png)

</details>

**任何其他有助于排查问题的信息**

或许 [decodeURIComponent\(\)](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent) 可用来处理这种情况。

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/219023561-0e9d0222-6d84-42e6-9197-4b18f2dd86bf.png)

</details>

**Comment by laggage** [comment]
[v1.6.4](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb)已修复

有问题欢迎再反馈
