### ISSUE TITLE
侧边栏分类列表显示子级分类

### ISSUE THREAD

**Issue by lky1433223** [cnblogs/vscode-cnb#129]
### ui上的哪部分与此新功能有关?

侧边栏控制台分类列表

### 新功能描述

能否同时显示子级分类？比如在A分类下存在子级分类B，现在是只能显示直接存放在分类A里的博文，能否显示自己分类B并展开显示B里的博文？

**Comment by laggage** [comment]
已支持 [v1.8.0](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb)
