### ISSUE TITLE
点击login无反应

### ISSUE THREAD

**Issue by menglongdeye** [cnblogs/vscode-cnb#130]
**问题描述**
安装插件后，点击login按钮无反应

**复现问题**
复现问题的步骤:
点击Login无反应

**期望的结果**
可以正常登录

**问题截图**
![image](https://user-images.githubusercontent.com/47941046/230895818-b6959da6-3140-44fe-bfe2-53f8b69030ff.png)

**环境信息:**
1.  电脑：MacBook Pro (16-inch, 2019)，macOS Catalina 10.15.7
2. 插件：博客园Cnblogs客户端 v1.7.1
3. vscode：March 2023 (version 1.77)

**任何其他有助于排查问题的信息**
原来是正常的，卸载了后重新装了最新版本不行了

**Comment by laggage** [comment]
可以先装回旧版，会尽快排查这个问题
<img width="477" alt="image" src="https://user-images.githubusercontent.com/38829279/230897311-725f885b-85cb-47e7-81dc-02b6f4cd8be4.png">

**Comment by laggage** [comment]
可以试试旧版中退出登录后，再更新到最新版可以正常登录吗

**Comment by menglongdeye** [comment]
挨个试了一下，1.65版本可以，从1.70开始不行了

**Comment by laggage** [comment]
我这里无法复现这个问题

提供一个离线安装包 [darwin-x64.zip](https://github.com/cnblogs/vscode-cnb/files/11196557/darwin-x64.zip)，下载后解压，手动安装试试，看看能不能正常登录

从本地文件安装插件的方式如图
<img width="556" alt="image" src="https://user-images.githubusercontent.com/38829279/231057093-4255f7e4-a53f-4def-a797-846b9436d1f3.png">

**Comment by laggage** [comment]
试试最新版本

先Close，有问题请继续反馈👀
