### ISSUE TITLE
设置自动提取本地图片后仍然无法提取

### ISSUE THREAD

**Issue by menglongdeye** [cnblogs/vscode-cnb#131]
**问题描述**
在设置中设置了自动提取本地照片，但是上传博客后图片显示异常

**期望的结果**
期望上传时自动转换本地图片

**问题截图**
1、设置界面
![image](https://user-images.githubusercontent.com/47941046/230907596-91c38567-12b3-44ad-8624-e4e1a129cc8b.png)
2、md文件
![image](https://user-images.githubusercontent.com/47941046/230907663-c86a951e-6789-47c2-b143-6faf230954c6.png)
3、上传后博客显示
![image](https://user-images.githubusercontent.com/47941046/230907746-36061e80-ac70-4ea8-8216-a13726b2c10b.png)

**环境信息:**
电脑：MacBook Pro (16-inch, 2019)，macOS Catalina 10.15.7
插件：博客园Cnblogs客户端 v1.6.5
vscode：March 2023 (version 1.77)

**Comment by laggage** [comment]
最新版中没有这个问题
