### ISSUE TITLE
无法添加 tag

### ISSUE THREAD

**Issue by Watware** [cnblogs/vscode-cnb#134]
**问题描述**
创建文章时 tag 栏不显示任何 tag，但能够添加新 tag

**复现问题**
新建 md 文件，上传博客园，编辑 tag 标签

**问题截图**
![img](https://img2023.cnblogs.com/blog/2878790/202304/2878790-20230419201819395-1378712551.jpg)

**环境信息:**
 - 操作系统: windows
 - vscode版本 1.76.1
 - vscode-cnb版本 1.7.1

**Comment by Watware** [comment]
我的账号是有tag的

**Comment by laggage** [comment]
已修复 [v1.7.2](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb)
