### ISSUE TITLE
授权成功后登录失败

### ISSUE THREAD

**Issue by 5i-wanna-be-the-666** [cnblogs/vscode-cnb#139]
**问题描述**
在使用该插件之后，点击登录跳转至博客园授权页面，授权成功后跳转回到vscode，显示登录即将成功。
然后界面并没有发生任何变化

**期望的结果**
成功登录，而不是再次请求授权

**问题截图**
![image](https://user-images.githubusercontent.com/58644245/236511594-dc1fd88d-094b-4131-900b-74acf79dc732.png)

**环境信息:**
 - 操作系统: windows
 - vscode版本 1.78.0

**Comment by laggage** [comment]
无法复现这个问题, 麻烦提供下下面的信息


- 电脑有没有使用代理? 有的话关掉试试
- vscode中有没有相关错误提示?

**Comment by 5i-wanna-be-the-666** [comment]
我在第一次使用时电脑开启了代理，但是后面关闭代理之后也是依然失败（在重启电脑之后也依然失败，我是否该在vscode中开启相应的代理？比如图中这样）
![image](https://user-images.githubusercontent.com/58644245/236624265-83f5e2d7-9fb4-47d3-9def-85817cb6d621.png)

vscode中并没有任何的输出提示，在出现即将登录成功的提示之后就结束了

**Comment by laggage** [comment]
> 我是否该在vscode中开启相应的代理

不应该使用代理，或者说应该把`*.cnblogs.com`加入代理白名单

vscode仓库里也看到了相关无法登录issue: [github login failed every time](https://github.com/microsoft/vscode/issues/160649)

好像是代理相关的设置导致的

尝试下面的方案
- 打开设置，搜索
- 取消勾选 `http.proxyStrictSSL`
- 设置 `http.proxySupport`为`off`
- 如图
  - 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/38829279/236635663-dad91944-dba3-4e02-81a7-dffc47048312.png">

**Comment by 5i-wanna-be-the-666** [comment]
感谢回复，不过我按照你的方法尝试之后还是失败了，同时我登录github是可以成功的，只有cnblog登录会失败
![image](https://user-images.githubusercontent.com/58644245/236651992-37ac03aa-31b4-4bdd-9e14-42f8e3d8acd8.png)

**Comment by fenzsen** [comment]
我和你一样的问题，还是没解决

**Comment by cnblogs-team** [comment]
@fenzsen 请问您登录时用的是什么浏览器？

**Comment by fenzsen** [comment]
用的Edge浏览器，换Chrome也是同样的效果。浏览器授权成功后跳转回vscode任然显示的是登录按钮，登录无效


仲阳十七
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnblogs/vscode-cnb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 中午11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnblogs/vscode-cnb] 授权成功后登录失败 (Issue #139)





 
@fenzsen 请问您登录时用的是什么浏览器？

**Comment by cnblogs-team** [comment]
@fenzsen 请问在浏览器地址栏中输入 `vscode://cnblogs.vscode-cnb` ，可以正常打开 vscode 吗？

**Comment by fenzsen** [comment]
点击打开，能正常打开vscode。



跳回浏览器之后，vscode右下角有提示正在登录。但过一会自动消失后依然没有登录，还只显示登录按钮。





仲阳十七
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnblogs/vscode-cnb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 下午2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnblogs/vscode-cnb] 授权成功后登录失败 (Issue #139)





 
@fenzsen 请问在浏览器地址栏中输入 vscode://cnblogs.vscode-cnb ，可以正常打开 vscode 吗？

**Comment by Thaumy** [comment]
于 Linux 环境下 Chromium 114.0.5735.198 复现。
请检查 [chrome://settings/content/popups](chrome://settings/content/popups) 是否禁用了相关选项。

**Comment by Thaumy** [comment]
该问题可能与 VSCode 版本有关
在 Linux 环境下，VSCode 1.80.0 并未产生此问题，而 1.73.1 下则存在此问题，且不能稳定复现，且对于 Chromium 和 FireFox，后者会更稳定一些。
在 Windows 10 下，VSCode 1.80.1, 1.73.1 和 1.78.2 均工作正常，使用 Edge 浏览器。
尝试更新浏览器或 VSCode 以解决该问题。

**Comment by cnblogs-team** [comment]
您好，麻烦您试试 1.8.8 是否还有这个问题

**Comment by 5i-wanna-be-the-666** [comment]
我在vsocde和edge浏览器依然复现这个问题
![image](https://github.com/cnblogs/vscode-cnb/assets/58644245/d97ddd2d-639e-4990-a5c0-c363dd75763d)

**Comment by Thaumy** [comment]
现已支持 PAT 登录，浏览器登录有问题的用户可以尝试使用 PAT。

**Comment by cnblogs-team** [comment]
您好，获取 PAT(personal accesstoken) 请访问 https://account.cnblogs.com/settings/account/personal-access-token
