### ISSUE TITLE
登录异常

### ISSUE THREAD

**Issue by joey5403** [cnblogs/vscode-cnb#140]
**问题描述**
点击Login后打开页面直接异常

**复现问题**
复现问题的步骤:
1.  安装插件后点击Login
2.  打开的登录页面里面只有报错

**期望的结果**
登录成功

**问题截图**
![image](https://user-images.githubusercontent.com/93772967/236599896-eb5d20f4-df56-440b-ab0a-f0cba876c52b.png)

**环境信息:**
 - 操作系统: linux 6.3.1-arch1-1 
 - vscode版本 1.78.0
 - vscode-cnb版本 v1.8.0

**任何其他有助于排查问题的信息**
在这里填写任何其他有助于排查问题的信息

**Comment by laggage** [comment]
现在试试呢？

**Comment by joey5403** [comment]
> 现在试试呢？

已经可以正常登录，非常感谢！
