### ISSUE TITLE
提取图片失败

### ISSUE THREAD

**Issue by SixPlusAndTimes** [cnblogs/vscode-cnb#149]
**问题描述**
我使用typora编辑好文版后，使用vscode打开并准备提取图片，但是提取图片失败了
![image](https://github.com/cnblogs/vscode-cnb/assets/42863829/a91125aa-4cf5-4c75-9cc4-040eb6bf76e0)
![image](https://github.com/cnblogs/vscode-cnb/assets/42863829/ffd41299-e567-47c8-9d63-c3e0453a5f60)

**Comment by cnblogs-team** [comment]
您好，麻烦您再试一下，如果还有问题，麻烦您将 markdown 文件与图片发邮件至 contact@cnblogs.com ，我们排查一下。

**Comment by cnblogs-team** [comment]
您好，问题的原因已经定位，是路径中包含括号`()`引起的
