### ISSUE TITLE
博客园语法扩展不可用

### ISSUE THREAD

**Issue by Thaumy** [cnblogs/vscode-cnb#165]
博客园语法扩展在 VSCode 中预览 markdown 时不可用，但导出 PDF 显示正常。

**Comment by cnblogs-dudu** [comment]
现在看多行引用 `>>>` 扩展语法可以正常使用，指定图片尺寸的扩展语法支持还没添加

**Comment by USTHzhanglu** [comment]
> 现在看多行引用 `>>>` 扩展语法可以正常使用，指定图片尺寸的扩展语法支持还没添加

![image](https://github.com/cnblogs/vscode-cnb/assets/56349457/23b281e8-4759-4e21-b757-1a5b84832ade)
这个多行引用是不是箭头写反了，用 <<<没效果诶

**Comment by cnblogs-dudu** [comment]
@USTHzhanglu 您好，抱歉，是写反了，我们会尽快更正
