### ISSUE TITLE
右下角的提示框停留时间有些久

### ISSUE THREAD

**Issue by cnblogs-dudu** [cnblogs/vscode-cnb#167]
<img width="750" alt="Screen_Shot_2023-07-28_at_09 29 56" src="https://github.com/cnblogs/vscode-cnb/assets/3196961/f902b5b7-269a-4d2b-99f7-75e1fd4f8795">

<img width="750" alt="Screen_Shot_2023-07-28_at_09 30 25" src="https://github.com/cnblogs/vscode-cnb/assets/3196961/18e369cb-444d-4bb8-b121-a4267745d74e">

**Comment by Thaumy** [comment]
VSCode 的 API 不允许这类提示被自动关闭，替代方案是使用带有进度条的提示，但此类提示不能被手动关闭，只能等待超时。

例如：

![image](https://github.com/cnblogs/vscode-cnb/assets/28834579/9aa008af-2e3a-4672-b083-2ed7f081df13)

Related: 
https://github.com/Microsoft/vscode/issues/2732
https://stackoverflow.com/questions/34893733/how-to-programmatically-close-vscode-windows-showinformationmessage-box

需要考虑替代方案的副作用是否可以接受。

**Comment by cnblogs-dudu** [comment]
那就算了，不用解决了
