### ISSUE TITLE
随笔列表分页功能存在问题

### ISSUE THREAD

**Issue by JerryYu2014** [cnblogs/vscode-cnb#169]
**问题描述**

随笔列表分页功能存在 bug

**复现问题**

复现问题的步骤:

1. 展开随笔列表
2. **<** 和 **>** 按钮处在禁用状态，无法进行上一页和下一页的操作

**期望的结果**

通过 **<** 和 **>** 按钮可对列表进行上一页和下一页的操作

**问题截图**

![image](https://github.com/cnblogs/vscode-cnb/assets/9960892/d2ba5b5f-3829-447d-af6b-50abea02c968)

**环境信息:**

 - 操作系统: Windows_NT x64 10.0.22621
 - VSCode版本: 1.80.2
 - 博客园扩展版本: v1.8.8

**Comment by Thaumy** [comment]
Fixed in: #170
