### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by evescn** [cnblogs/vscode-cnb#171]
**问题描述**

在 vscode 中，安装 博客园插件进行博客编辑，上传本地图片或者剪切板图片到博客园失败

**复现问题**

1、vscode Cnblogs 目录下，分类目录下 ，新建一个 xxx.md 文档博客
2、进行截图，右键选择 剪切板图片 上传，或者选择本地图片上传都是失败
3、vscode 右下角失败信息：上传图片失败, read ECONNRESET

**期望的结果**

成功上传图片

**环境信息:**

 - 操作系统: [macOS 11.6]
 - VSCode版本 [1.80]
 - 博客园扩展版本 [v1.8.8]

**Comment by evescn** [comment]
> 请问扩展升级到1.8.9版本后还存在此问题吗？

我升级到 1.8.9 之后，第一次还是无法正常上传本地图片，或者剪切板图片，只是说vscode 右下角没有报错啦，但是上传后，md 文档地址，没有自动填充 图片上传后的 url 地址信息：![](http://.........)

我还录制了一个视频，但是发现太大了，无法上传 github。

我又重新录制视频的时候，发现已经可以上传图片，和剪切板图片了。

但是发现使用快捷键方式上传剪切板图片依旧回报错：vscode 右下角失败信息：上传图片失败, read ECONNRESET。使用 快捷键方式上传本地图片，直接没有相应（之前版本也没有这2个快捷键的）

而使用右键，直接选择本地图片上传和剪切板图片上传可以成功，使用快捷键报错

**Comment by evescn** [comment]
我把第一次和第二次的视频，直接回复邮件。但我不知道你能否收到，还是说那个邮件是github 带转发过来的

**Comment by cnblogs-team** [comment]
@evescn 您好，视频可以发邮件至 contact@cnblogs.com

**Comment by evescn** [comment]
好的

**Comment by Higurashi-kagome** [comment]
有一个类似的情况：

1. 设置自动提取所有图片或自动提取网络图片
2. 新建博文，在博文中加入网络图片，比如`![epub_27651657_642](https://res.weread.qq.com/wrepub/epub_27651657_642)`
3. 上传博文（选择新建）
4. 发现没有提取网络图片

扩展版本：1.8.9

VSCode：

```
版本: 1.81.1 (user setup)
提交: 6c3e3dba23e8fadc360aed75ce363ba185c49794
日期: 2023-08-09T22:22:42.175Z
电子: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by Thaumy** [comment]
> 有一个类似的情况：
> 
> 1. 设置自动提取所有图片或自动提取网络图片
> 2. 新建博文，在博文中加入网络图片，比如`![epub_27651657_642](https://res.weread.qq.com/wrepub/epub_27651657_642)`
> 3. 上传博文（选择新建）
> 4. 发现没有提取网络图片
> 
> 如果包含本地图片，上传博文时会提示在提取图片，但博文上传成功后没有在正确的位置替换本地图片链接（而是将链接插在了博文的其他位置）。
> 
> 扩展版本：1.8.9
> 
> VSCode：
> 
> ```
> 版本: 1.81.1 (user setup)
> 提交: 6c3e3dba23e8fadc360aed75ce363ba185c49794
> 日期: 2023-08-09T22:22:42.175Z
> 电子: 22.3.18
> ElectronBuildId: 22689846
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.22621
> ```

目前提取图片仅支持带有后缀的图片引用，例如 ![img](https://foo.bar.baz/img.jpg)。以后会考虑实现更加全面的图片资源识别。

**Comment by Higurashi-kagome** [comment]
嗯，测了有后缀时是正常的，确实是因为没有后缀。

[test.zip](https://github.com/cnblogs/vscode-cnb/files/12334246/test.zip) 中的 test.md 应该能复现这种情况。

**Comment by cnblogs-dudu** [comment]
您好，已在 `v1.8.36` 支持提取不带扩展名的图片文件
