### ISSUE TITLE
无法上传/获取博文

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#172]
**问题描述**

上传博文失败。

**复现问题**

复现问题的步骤:

1. 新建一个 md 文件，加入内容
2. 在 VSCode 的右上角中，找到上传博文按钮，点击按钮
3. 在弹出的窗口中选择“新建博文”
4. 提示“出现未知错误。有关详细信息，请参阅日志”

**期望的结果**

正确上传博文。

**问题截图**

<details>
<summary>Details</summary>

![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/c126289c-4ba7-4507-b163-c751bb838107)

</details>

**环境信息:**

 - 操作系统: [e.g. Win11]
 - VSCode版本 [1.81.0]
 - 博客园扩展版本 [1.8.8]

**任何其他有助于排查问题的信息**

实际上也无法博文分类、博文列表、闪存等，处于一种不可用状态：

<details>
<summary>Details</summary>

![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/0bedfd6e-1d92-4586-b3f6-a103252ab7d6)

</details>

**Comment by cnblogs-team** [comment]
您好，我们会尽快修复这个问题。

**Comment by Thaumy** [comment]
请问将扩展升级到 1.8.9 版本能够复现此问题吗？

**Comment by Higurashi-kagome** [comment]
重新登录后可正常使用。谢谢。
