### ISSUE TITLE
博文列表分页数显示错误，且无法跳转下一页

### ISSUE THREAD

**Issue by laggage** [cnblogs/vscode-cnb#173]
**问题描述**

博文列表分页数显示错误，且只能展示一页

**复现问题**

复现问题的步骤:

1. 插件面板
2. 展开博文列表
3. 无法去下一页，页数展示错误（搜索也是，明明找到了，却显示0篇）

<img width="212" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/38829279/d9e59c21-d49b-4bc2-a8a5-e19e216f3ffb">

<img width="329" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/38829279/473069fa-5dff-45b2-ae4f-2b513f313ab3">

**期望的结果**

正确展示分页数，可以点击点击下一页

**环境信息:**

 - 操作系统: macOS 13.4.1 (c) (22F770820d)
 - VSCode版本 
 ```
Version: 1.80.2 (Universal)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T21:05:41.366Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0
 ```
 - 博客园扩展版本 1.8.8

**任何其他有助于排查问题的信息**

回退至 **1.8.6** 版本后才恢复，#172 好像也是

**Comment by laggage** [comment]
是不是大改了什么啊？考虑先回退一下？ @Thaumy @cnblogs-dudu

**Comment by cnblogs-team** [comment]
您好，我们会尽快修复这个问题。

**Comment by Thaumy** [comment]
Fixed in: #170

**Comment by Thaumy** [comment]
Fixed in: #170
