### ISSUE TITLE
支持从命令面板调用常用命令

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#176]
### UI 上的哪个部分与此新功能有关?

其他

### 新功能描述

在 #37 和 #47 中有提到开放`保存到博客园`命令和`在线查看博文`命令，支持从命令面板调用（进而方便通过快捷键操作）。之后有支持该功能，但最近的更新（当前扩展版本 v1.8.10）似乎将其关闭了。

### [选填]建议的解决方案

对常使用快捷键的用户来说提供命令入口会很方便，建议恢复。

**Comment by Thaumy** [comment]
您好。在扩展的 1.8.10 版本中这些命令依然可用，也可以绑定到快捷键。
最近的更改变更了部分命令的名称，这可能导致一些原有的快捷键绑定失效，您可以进行重新绑定。

**Comment by Higurashi-kagome** [comment]
好的，命令确实可用，只是更改了名称。谢谢。
