### ISSUE TITLE
随笔列表无内容

### ISSUE THREAD

**Issue by TengshengHou** [cnblogs/vscode-cnb#181]
**问题描述**

随笔列表无内容

**复现问题**

复现问题的步骤:

token 过期后重新登陆

**期望的结果**

你期望的结果

**问题截图**

![image](https://github.com/cnblogs/vscode-cnb/assets/29135622/1d04be7a-916e-4946-a67e-cb3e33cddc5c)

**环境信息:**

 - 操作系统: [e.g. macOS]
 - VSCode版本 [e.g. 1.00.0]
 - 1.81.1
 - 博客园扩展版本 [e.g. 1.0.0]
v1.8.13
**任何其他有助于排查问题的信息**

在这里填写任何其他有助于排查问题的信息

**Comment by cnblogs-team** [comment]
您好，已在 1.8.15 版中修复。抱歉，给您带来麻烦了。
