### ISSUE TITLE
随笔列表无内容，工作空间自己指定后不生效

### ISSUE THREAD

**Issue by iven98** [cnblogs/vscode-cnb#184]
**问题描述**

随笔列表无内容，工作空间自己指定后不生效

**Comment by cnblogs-dudu** [comment]
工作空间指定后不生效的问题是在 `1.8.8` 开始引入的，`1.8.7` 没这个问题

**Comment by cnblogs-dudu** [comment]
工作空间指定后不生效的问题是在异步方法中调用同步方法 `fs.existsSync` 引起的

**Comment by cnblogs-team** [comment]
您好，已在 1.8.15 版中修复。抱歉，给您带来麻烦了。
