### ISSUE TITLE
随笔列表为空

### ISSUE THREAD

**Issue by myheartwaving** [cnblogs/vscode-cnb#188]
**问题描述**

随笔列表为空

**复现问题**

复现问题的步骤:

登录，点开随笔列表，发现为空

**期望的结果**

和博客后台一样显示所有随笔

**问题截图**
![](https://github.com/cnblogs/vscode-cnb/assets/99001434/0b1aac90-ee90-4ac0-85b2-62a51e81a383)

**环境信息:**

 - 操作系统: [Windows 11]
 - VSCode版本 [1.81.1]
 - 博客园扩展版本 [1.0.0]

**任何其他有助于排查问题的信息**
昨天vscode会报一个什么Error:state is undefined的错，现在不报了，但是还是拉取不到随笔

**Comment by myheartwaving** [comment]
最后一次测试是在8.27 22:30，仍然无法正常显示随笔

**Comment by cnblogs-team** [comment]
抱歉，在进一步修复中

**Comment by cnblogs-team** [comment]
您好，已在 1.8.16 中修复。抱歉，给您带来麻烦了。

**Comment by myheartwaving** [comment]
> 您好，已在 1.8.16 中修复。抱歉，给您带来麻烦了。

我这边能正常使用了，辛苦了
