### ISSUE TITLE
点击搜索结果中的设置图标出错

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#195]
**问题描述**

点击搜索结果中的设置图标、拉取博文图标出错（删除图标未测试、点击上传博文图标能正常工作）。

**复现问题**

复现问题的步骤:

1. 进入随笔列表，点击搜索
2. 搜索一篇已经发布的博文
3. 搜索到后，点击搜索结果中该博文右侧的设置图标
4. 报错`Error running command vscode-cnb.post.modify-setting`

**期望的结果**

正常运行图标对应的命令。

**问题截图**

<details>
<summary>Details</summary>

![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/ae0ce72f-3e72-4465-b395-909319a8fb6c)

</details>

**环境信息:**

```
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
``` 

 - 博客园扩展版本 v1.8.18

**Comment by cnblogs-team** [comment]
您好，已在 v1.8.20 中采用临时方法修复
