### ISSUE TITLE
在连接博客园与vscode时出现问题

### ISSUE THREAD

**Issue by dyccyber** [cnblogs/vscode-cnb#199]
输入token之后
显示
<img width="175" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/129243050/0f146b1c-3782-4ab1-8640-866e7c6e50b3">
但是一直显示用户未授权
什么信息也获取不了
并且无法退出

**Comment by cnblogs-team** [comment]
您好，麻烦您试试点击 vscode 左下角的按钮对扩展进行授权

**Comment by cnblogs-team** [comment]
您好，麻烦您试试点击 vscode 左下角的账号（Accounts）按钮对扩展进行授权

**Comment by dyccyber** [comment]
thanks
