### ISSUE TITLE
没有右键菜单

### ISSUE THREAD

**Issue by TengshengHou** [cnblogs/vscode-cnb#20]
**问题描述**
没有右键菜单

**复现问题**
1.登陆插件
2.打开文章
3.在对应文章的编辑器内右键

**期望的结果**
应该有博客园的同步文章等菜单

**问题截图**
![image](https://user-images.githubusercontent.com/29135622/148475629-39e8828d-066a-4fb9-81b2-b42102dd9142.png)

**环境信息:**
 
 - vscode版本1.63.2
 - vscode-cnb版本 v0.0.15

**Comment by laggage** [comment]
编辑器位置的右键菜单只对markdown类型的文件起作用，但是仍然可以编辑富文本博文(html)并保存

![image](https://user-images.githubusercontent.com/38829279/148488789-dda50422-8eb4-44ac-bc5a-06026591c402.png)
