### ISSUE TITLE
不能设置发布选项,一直报错

### ISSUE THREAD

**Issue by Philofallever** [cnblogs/vscode-cnb#200]
**问题描述**

![image](https://github.com/cnblogs/vscode-cnb/assets/15180187/beac3f14-96db-4f65-9dc7-197cf368cdbf)

**复现问题**
1. 切换到cnblogs视图
2. 选中一个随笔列表中的列表
3. 点击齿轮

**Comment by cnblogs-team** [comment]
您好，抱歉，让您久等了，该问题已在 1.8.23 中修复
