### ISSUE TITLE
上传博文未更新

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#203]
**问题描述**

修改已发布的博文后上传，发现修改未更新。

**复现问题**

复现问题的步骤:

1. 新建一篇博文并上传（Markdown）
2. 修改博文内容后重新上传
3. 发现修改的内容未更新到博客园

**期望的结果**

上传后更新最新内容到博客园。

**环境信息**

```
版本: 1.82.2 (user setup)
提交: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
日期: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

- 扩展 v1.8.21

**任何其他有助于排查问题的信息**

更详细一点的话：

1. 新建一篇博文并上传（Markdown），上传时不勾选“发布”
2. 修改博文内容后再次上传，发现未更新
3. 点击博文的“设置”图标，勾选“发布”后提交，发现内容成功更新
4. 继续修改博文内容并上传，发现未更新

**Comment by cnblogs-team** [comment]
您好，收到您的反馈，争取今天修复这个问题

**Comment by cnblogs-team** [comment]
您好，问题已定位，修复需要一些时间，麻烦您先通过右键菜单中的“上传到博客园”上传

**Comment by cnblogs-team** [comment]
您好，抱歉，让您久等了，该问题已在 1.8.23 中修复

**Comment by Higurashi-kagome** [comment]
我这里测试未成功更新，步骤如下：

1. 因为这段时间扩展不能更新博文，所以我安装了 1.8.18 版本
2. 在扩展管理中更新扩展至最新（v1.8.23）
3. 安装后 VSCode 提示需要重新加载，所以重新加载（重启 VSCode）
4. 选择一篇已经发布的博文，编辑其内容
5. 发布博文，发现博文未更新

**Comment by cnblogs-team** [comment]
@Higurashi-kagome 请问您是具体通过哪个操作发布博文的？插件中没有`发布博文`的按钮

**Comment by Higurashi-kagome** [comment]
嗯，是`上传到博客园`：

<details>
<summary>Details</summary>

![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/9ab83516-f1bb-4625-acc3-16172a903bbf)

</details>

我给这个命令绑定了快捷键，先是使用快捷键上传，然后尝试通过点击图标上传：

<details>
<summary>Details</summary>

![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/9348d3a3-c0e7-4d26-aca6-bfc68fe22cd2)

![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/4d2eabe0-7f49-4ca7-a435-327324e58f4f)

</details>

**Comment by cnblogs-team** [comment]
@Higurashi-kagome 您好，很奇怪，我们现在怎么测试都无法重新这个问题，请问点击上传按钮后会出现`上传成功`的提示吗？

**Comment by Higurashi-kagome** [comment]
有提示`上传成功`，另外打开博文设置，点击确定后能够正常更新：

<details>
<summary>Details</summary>

![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/195056ea-c6bc-4f71-9fef-65fdd24b9dfb)

</details>

**Comment by cnblogs-team** [comment]
您好，麻烦您更新至 1.8.25 看问题是否已解决

**Comment by Higurashi-kagome** [comment]
已能够正常更新。
