### ISSUE TITLE
一直报未授权的错

### ISSUE THREAD

**Issue by Zhx-Cl** [cnblogs/vscode-cnb#207]
**问题描述**

一直报未授权的错，但是左侧已经有功能列表了

**复现问题**
使用授权码登录就会出现这个问题
![image](https://github.com/cnblogs/vscode-cnb/assets/81512799/48ab3467-ae77-47fd-811b-eaa5af1176c1)

**期望的结果**

你期望的结果

如果可能的话, 提供下遇到问题时的截图以便排查

**环境信息:**

 - 操作系统: [win10]
 - VSCode版本 [1.82]
 - 博客园扩展版本 [1.8.21]

**任何其他有助于排查问题的信息**

在这里填写任何其他有助于排查问题的信息

**Comment by saleo** [comment]
+1: 

Version: 1.83.0-insider (user setup)
Commit: 4268e464763087044d0c1b5bdd37ebbe683cadfa
Date: 2023-09-29T20:42:50.630Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by cnblogs-team** [comment]
@Zhx-Cl @saleo 该问题已在 v1.8.27 中修复
