### ISSUE TITLE
Linux下，vs-code插件，v1.8.21，保存文章的时候报400错误：操作失败: 400 Bad Request: {"errors":["内容不能为空"],"type":0}，而同样的操作同样的版本在Windows下没有问题

### ISSUE THREAD

**Issue by tekikesyo** [cnblogs/vscode-cnb#208]
**问题描述**

Linux下，vs-code插件，v1.8.21，保存文章的时候报400错误：操作失败: 400 Bad Request: {"errors":["内容不能为空"],"type":0}，而同样的操作同样的版本在Windows下没有问题

**复现问题**

新建博文按钮，新建空白的md文件，随便输入，在弹出的保存框里适当填写，点击保存。

**期望的结果**

**问题截图**
操作失败: 400 Bad Request: {"errors":["内容不能为空"],"type":0}

**环境信息:**
版本: 1.82.2
提交: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
日期: 2023-09-14T05:51:20.981Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 4.19.112-2.el8.x86_64

插件版本：v1.8.21

**任何其他有助于排查问题的信息**

**Comment by cnblogs-team** [comment]
您好，麻烦您更新至 1.8.25 看问题是否已解决
