### ISSUE TITLE
账户信息点击“我的主页”后，跳转的个人主页不对。

### ISSUE THREAD

**Issue by Wing-summer** [cnblogs/vscode-cnb#21]
我的昵称是寂静的羽夏，而我的博客是`wingsummer`，这会导致跳转的连接是`https://home.cnblogs.com/u/寂静的羽夏`而不是 `https://home.cnblogs.com/u/wingsummer`，从而导致错误

**Comment by laggage** [comment]
感谢反馈，已经修复啦，升级最新版本即可
