### ISSUE TITLE
VS Code 中通过cnblog插件无法选择本地gif图片上传

### ISSUE THREAD

**Issue by LuBu0505** [cnblogs/vscode-cnb#22]
**问题描述**
VS Code 中通过cnblog插件无法选择本地gif图片上传

**复现问题**
复现问题的步骤:
在VS Code中，新建一个.md文件，用于编写新博客。
右键选择从本地上传文件，弹出的对话框中，无法选择GIT图片

**期望的结果**
能够选择gif动图

**问题截图**
![cannot select gif](https://user-images.githubusercontent.com/69841770/148639083-7d199b56-3217-449f-b46b-0ae43ef71dc8.png)

**环境信息:**
 - 操作系统: [e.g. iOS]
 - vscode版本 [e.g. 1.63.2]
 - vscode-cnb版本 [e.g. 0.0.13]

**任何其他有助于排查问题的信息**
在这里填写任何其他有助于排查问题的信息

**Comment by laggage** [comment]
感谢反馈，已经修复啦，升级最新版本即可
