### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by kierankihn** [cnblogs/vscode-cnb#220]
**问题描述**

博客园 VSCode 插件无法正常登录

**复现问题**

复现问题的步骤:

- 博客园插件中选择浏览器/令牌登录
- 授权后仍然显示未登录

**期望的结果**

成功登录博客园账户

**问题截图**

发生问题的录屏：[link](https://kierankihn-my.sharepoint.com/:v:/g/personal/doubleki_xljzt_onmicrosoft_com/Eb8EyVy6HXtOj7gPQnPxGGIBp2NBfwxB14s0NUNzN6eTlQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=YqMGPZ)

**环境信息:**

 - 操作系统：
Windows 10 21H2 19043.1023
 - VSCode版本：
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19043
 - 博客园扩展版本：
v1.8.28

**任何其他有助于排查问题的信息**

VSCode Extension Host 的错误日志：
```
2023-10-12 08:23:05.328 [error] invalid type: null, expected a string vscode-cnb.login.web {"value":"cnblogs.vscode-cnb","_lower":"cnblogs.vscode-cnb"}
2023-10-12 08:23:11.796 [error] invalid type: null, expected a string vscode-cnb.login.pat {"value":"cnblogs.vscode-cnb","_lower":"cnblogs.vscode-cnb"}
```

**Comment by cnblogs-team** [comment]
您好，这个问题与账号没有开博客有关，我们正在针对这个问题进行改进

**Comment by cnblogs-team** [comment]
您好，已在 v1.8.29 中改进，现在可以登录了，登录后会提示开通博客
