### ISSUE TITLE
增加对<img>图像的提取

### ISSUE THREAD

**Issue by zh-jp** [cnblogs/vscode-cnb#221]
### UI 上的哪个部分与此新功能有关?

Markdown 编辑器右键上下文菜单

### 新功能描述

- 现在插件仅能对“\!\[\]\(\)”格式的图片提取;
- 这种格式在图片需要居中的情况下（用\<center>\</center>修饰）博客园网页无法正常显示图片。
- 但\<img src='./test.png'>这种图片插入目前还不能进行提取。

能否增设识别<img>的图片提取，谢谢！

**Comment by cnblogs-dudu** [comment]
您好，已在 `v1.8.36` 修复，是正则表达式的问题引起，本来是支持的。
