### ISSUE TITLE
vscode中操作任何动作失效

### ISSUE THREAD

**Issue by gujie1911509826** [cnblogs/vscode-cnb#223]
**问题描述**

点击左侧图标，里面每栏下面都提示"There is no data provider registered that can provide view data." ，且点击每栏旁边的刷新按钮vscode提示"Error running command vscode-cnb.post-category.refresh: command 'vscode-cnb.post-category.refresh' not found. This is likely caused by the extension that contributes vscode-cnb.post-category.refresh." 
我试图卸载重新安装登陆也无济于事，仿佛已经是登陆态，再markdown文件中右键中选择任何操作均不生效，
![image](https://github.com/cnblogs/vscode-cnb/assets/54139911/8c4927a5-8847-4d68-b541-8509cbd23cbb)

**复现问题**

复现问题的步骤:

好像是刚不久vscode提示我更新vscode，我就点了updata，之后就不可以了

**期望的结果**

卸载之后可以正常重新登陆 且可使用

**问题截图**

**环境信息:**

 - 操作系统: macOS
 - VSCode版本  September 2023 (version 1.83)
 - 博客园扩展版本 v1.8.29
 - 
**任何其他有助于排查问题的信息**

无

**Comment by cnblogs-team** [comment]
您好，我们这里无法重现这个问题，麻烦您安装 v1.8.28 看是否还有这个问题

**Comment by gujie1911509826** [comment]
resolved
