### ISSUE TITLE
为什么我安装了插件一直上传不了文章，是我哪里配置不对嘛？

### ISSUE THREAD

**Issue by yansongwel** [cnblogs/vscode-cnb#224]
**问题描述**

提交文章失败

提交文章的报错
<img width="1291" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/73923867/816128f7-7563-4290-8472-9169bfa45b22">

博客园登录成功
<img width="653" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/73923867/2cca9c32-9d02-44c1-9681-d7422749d49c">

插件中的工作空间没有任何反应和报错
<img width="607" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/73923867/8e47bdd7-363e-41bd-b80e-2a8b5f922114">

**复现问题**

复现问题的步骤:

默认安装完插件，我关联了博客园的登录toke，就是文章一直上传不了，文章工作区也创建不了

**期望的结果**

你期望的结果

**问题截图**

如果可能的话, 提供下遇到问题时的截图以便排查

**环境信息:**

 - 操作系统: windows 11
 - VSCode版本 1.83.1
 - 博客园扩展版本 当前最新

**任何其他有助于排查问题的信息**

在这里填写任何其他有助于排查问题的信息

**Comment by qiqicliff** [comment]
基本上所有的功能都是未找到命令，求解

**Comment by cnblogs-team** [comment]
您好，请问您使用的操作系统是什么？

**Comment by qiqicliff** [comment]
![image](https://github.com/cnblogs/vscode-cnb/assets/103885652/4f68695c-bbca-4f28-9fb8-2713b3cd5142)
命令不存在：
![image](https://github.com/cnblogs/vscode-cnb/assets/103885652/ba1d0c29-cb19-4638-bd89-3da9517f68ed)
![image](https://github.com/cnblogs/vscode-cnb/assets/103885652/5d305767-9403-45aa-93e7-84215cc9075a)
版本：
![image](https://github.com/cnblogs/vscode-cnb/assets/103885652/f2c7a6e9-0017-4694-9cea-c524f4c0473e)

**Comment by qiqicliff** [comment]
应该是vscode的问题，picgo也是出问题了
![image](https://github.com/cnblogs/vscode-cnb/assets/103885652/fdbfa65b-c7a6-4478-9920-66146ea589fa)

**Comment by cnblogs-team** [comment]
您好，问题很奇怪，我们这里使用 vscode 1.83.1 没有出现这个问题，我们正在想办法重现这个问题

**Comment by yansongwel** [comment]
你可以用虚拟机，虚拟一个win11全新系统，默认安装一遍vscode 插件  就把问题复现了。我怀疑你们本地应该是事先安装了什么依赖所以是没有问题的。  希望你们尽快解决，我这边还有很多文档等着上传

**Comment by cnblogs-team** [comment]
@yansongwel 我们这样试过了，没能重现，麻烦您换一个以前的版本安装试试

**Comment by yansongwel** [comment]
@cnblogs-dudu 你是指什么换一个以前得版本试试   插件还是vscode 还是什么？

**Comment by cnblogs-team** [comment]
@yansongwel 您好，是插件

**Comment by yansongwel** [comment]
@cnblogs-team 插件，我是直接通过vscode得默认插件里边搜索安装得。这个没有办法指定版本安装把

**Comment by cnblogs-team** [comment]
@yansongwel 您好，在“默认插件里边搜索”后，点击插件的设置按钮，在菜单中可以安装其他版本

**Comment by cnblogs-team** [comment]
@yansongwel 麻烦您进入 `%userprofile%\.vscode\extensions` 删除所有 `cnblogs.vscode-cnb-` 开头的文件夹，然后安装最新版插件试试

**Comment by qiqicliff** [comment]
> @yansongwel 麻烦您进入 `%userprofile%\.vscode\extensions` 删除所有 `cnblogs.vscode-cnb-` 开头的文件夹，然后安装最新版插件试试

有用，问题已解决。谢谢！！
