### ISSUE TITLE
原先的工作空间的目录调整成一个新的目录，但是博客下载的时候，还是下到旧的工作空间目录

### ISSUE THREAD

**Issue by GreyZeng** [cnblogs/vscode-cnb#227]
**问题描述**

原先的工作空间的目录调整成一个新的目录，但是博客下载的时候，还是下到旧的工作空间目录

**复现问题**

复现问题的步骤:

1. 设置工作空间为：A目录，然后下载几篇博客，都在A目录下
2. 然后调整工作空间为：B目录，删除A目录，再次下载这几篇博客，还是在A目录下

**期望的结果**

设置完毕工作空间后，再次下载的博客应该到新的工作空间目录中

**Comment by dancefingerx** [comment]
我也出现这个问题，有解决吗？

**Comment by cnblogs-team** [comment]
您好，收到您反馈的问题，我们这周会尽快解决

**Comment by cnblogs-team** [comment]
@GreyZeng @dancefingerx 已在 v1.8.31 中修复

**Comment by GreyZeng** [comment]
> @GreyZeng @dancefingerx 已在 v1.8.31 中修复

空间已经调整对了，但是目录错了，

## 问题描述

在【分类列表】里面点击每个分类下的文章（比如：工作空间是 X，在随笔分类下 Y 分类下有一篇 A 文章），原先是是下载到 X目录下的 Y 目录下，但是现在都只下载到了 X 目录下。

**Comment by GreyZeng** [comment]
> @GreyZeng @dancefingerx 已在 v1.8.31 中修复

工作空间已经调整对了，但是下载的目录又错了，

问题描述
在【分类列表】里面点击每个分类下的文章（比如：工作空间是 X，在随笔分类下 Y 分类下有一篇 A 文章），原先是是下载到 X目录下的 Y 目录下，但是现在都只下载到了 X 目录下

**Comment by dancefingerx** [comment]
> @GreyZeng @dancefingerx 已在 v1.8.31 中修复

没有被修复啊，还是下载到了旧的工作空间，我这是windows10系统，之前设置工作空间为s:\blogs。之后更改工作空间为s:\Cnblogs，但是还是有部分博文下载到了原来的工作空间s:\blogs中。请看看是怎么回事。

**Comment by cnblogs-team** [comment]
@GreyZeng @dancefingerx 抱歉，已进一步修复，麻烦安装 `v1.8.35` 试试

**Comment by GreyZeng** [comment]
> @GreyZeng @dancefingerx 抱歉，已进一步修复，麻烦安装 `v1.8.35` 试试

并没有解决呀，在【分类列表】下，我下载下来的博客，还是在工作空间的根目录下，而不是分类对应的文件夹下，如图

![QQ截图20231124233948](https://github.com/cnblogs/vscode-cnb/assets/12782103/a0e54316-b406-4506-b674-471c8861a1a7)

**Comment by dancefingerx** [comment]
@cnblogs-team 谢谢，辛苦，但是很遗憾的是并未修复。

当前版本：
![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/674dd778-d739-4243-8ae3-8abc5f969e79)

设置的工作空间 S:\Cnblogs\ ：
![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/6aefb726-ac25-46b1-bffb-d78a28e5358f)

随笔下载位置 S:\Blogs\ ：
![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/f6a94852-5321-49bf-8805-de2738f0b164)

只有部分下载到设置的工作空间中：
![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/1b49214d-634f-46d9-89a0-825d212d690c)

**Comment by cnblogs-team** [comment]
@dancefingerx 您好，请问您是如何下载的？修改工作空间后重新拉取博文才会下载到新的工作空间

**Comment by dancefingerx** [comment]
> @dancefingerx 您好，请问您是如何下载的？修改工作空间后重新拉取博文才会下载到新的工作空间

我是直接点击博文，它自动下载的

**Comment by dancefingerx** [comment]
我知道什么原因了。
当博文第一次下载后，这里会记住上一次下载位置，如果删除本地博文，然后重新点击的时候，它会自动下载到这里记录的上一次下载位置，要想下载到工作空间，需要点击“拉取”按钮，这个本地地址才会更新。
![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/92528bc4-1669-4da3-9d1c-9bfc9f43c1f2)

这个记录上一次下载位置点击自动重新下载到原处（而不是检查工作空间地址，然后下载到新工作空间）的机制是就这么设计的么？

![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/dbf73104-7a6d-45d3-9eae-6dfec0804384)

**Comment by cnblogs-team** [comment]
@dancefingerx 您好，我们会针对这个情况进行改进

**Comment by cnblogs-team** [comment]
@dancefingerx 已更进一步修复，麻烦安装 `v1.8.37` 试试

**Comment by cnblogs-dudu** [comment]
#243 会引起问题 #250

**Comment by dancefingerx** [comment]
> @dancefingerx 您好，我们会针对这个情况进行改进

@cnblogs-team 你好，经过测试问题依然存在，先点击随笔列表博文，然后删除原来工作空间目录，再修改新工作空间目录，再次点击之前已经点击过的随笔列表博文，下载位置依然是之前的工作空间目录。

![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/c9501cd6-42b3-4f6a-ba4e-c1c7d53a29e5)

![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/76926395-42ee-41cd-a818-e940ce3c6dcf)

**Comment by cnblogs-team** [comment]
@dancefingerx 您好，由于之前的修复会引起 #250，后来回退了，待重新修复

**Comment by cnblogs-team** [comment]
@dancefingerx 您好，已在 `v1.8.47` 中改进，现在在修改工作空间目录时会自动更新博文关联路径，路径中的旧工作空间目录会替换为新工作空间目录

**Comment by dancefingerx** [comment]
![image](https://github.com/cnblogs/vscode-cnb/assets/46144385/010d8cb9-6ce6-4ff0-8098-43f28a86674b)


@cnblogs-team 你好，刚刚测试了下，还是有问题，就是发现你们这次更新的结果好像是把以前的工作空间目录和现在的工作空间目录拼接接后形成新目录。
当前情况如下：
原来的工作空间目录为： S:\Blogs\
新工作空间目录为：S:\Cnblogs\
v1.8.48版本情况是：S:\CnblogsBlogs\

**Comment by cnblogs-team** [comment]
@dancefingerx 抱歉，已定位问题的原因，预计明天会修复

**Comment by cnblogs-team** [comment]
@dancefingerx 您好，已在 `v1.8.49` 中修复，麻烦您再试试
