### ISSUE TITLE
上传本地图片时一直卡住

### ISSUE THREAD

**Issue by GreyZeng** [cnblogs/vscode-cnb#231]
**问题描述**

写博客的时候，上传本地图片，进度条一直卡着

**复现问题**

复现问题的步骤:

1. 编辑博客
2. 点击上传本地图片
3. 图片上传进度一直卡住

![微信截图_20231123223356](https://github.com/cnblogs/vscode-cnb/assets/12782103/a532d864-9fdd-4a64-89a6-61fd0928dda7)

**Comment by cnblogs-team** [comment]
您好，麻烦您在 vscode 的 `Help` 菜单中点击 `Toggle Developer Tools`，看一下控制台是否有对应的报错信息

**Comment by GreyZeng** [comment]
> 您好，麻烦您在 vscode 的 `Help` 菜单中点击 `Toggle Developer Tools`，看一下控制台是否有对应的报错信息
显示这个报错：
![微信截图_20231123223356](https://github.com/cnblogs/vscode-cnb/assets/12782103/cd5e12d0-1384-49cf-b637-db75c4d512d7)

@cnblogs-team

**Comment by cnblogs-team** [comment]
您好，发现问题了，多个了`C:\`，明天会找时间修复

**Comment by cnblogs-team** [comment]
您好，已在 v1.8.33 中修复
