### ISSUE TITLE
运行命令 vscode-cnb.* 错误: command 'vscode-cnb.*' not found。这可能是由提交 vscode-cnb.*的扩展引起的。

### ISSUE THREAD

**Issue by HaiJeng** [cnblogs/vscode-cnb#245]
**问题描述**

运行命令 vscode-cnb.* 错误: command 'vscode-cnb.*' not found。这可能是由提交 vscode-cnb.*的扩展引起的。

**复现问题**

运行1.8.37、1.8.36、1.8.33都出现了以上的问题，版面不加载并且或报如标题的错误

**问题截图**

![image1](https://github.com/cnblogs/vscode-cnb/assets/49520520/cbaf2bbd-20a4-4f01-a3f2-327aec16924d)
![image2](https://github.com/cnblogs/vscode-cnb/assets/49520520/8b845276-4b7c-4c99-b8e0-3b33e81ba0b5)

**环境信息:**

 - 操作系统: [e.g. macOS]
   - Windows11
 - VSCode版本 [e.g. 1.00.0]
   - 1.84.2
 - 博客园扩展版本 [e.g. 1.0.0]
   - 1.8.37
   - 1.8.36
   - 1.8.33

**任何其他有助于排查问题的信息**

通过降低安装版本到1.8.27可解决此问题

**Comment by cnblogs-team** [comment]
您好，麻烦您打开 `%userprofile%\.vscode\extensions` 目录，删除所有 `cnblogs.vscode-cnb-` 开头的文件夹，然后安装最新版插件试试

**Comment by HaiJeng** [comment]
> 您好，麻烦您打开 `%userprofile%\.vscode\extensions` 目录，删除所有 `cnblogs.vscode-cnb-` 开头的文件夹，然后安装最新版插件试试

我按照您说的方法尝试了2次，但是依然还是报上面的错误。

**Comment by cnblogs-team** [comment]
您好，麻烦您在 vscode 的 Help 菜单中点击 Toggle Developer Tools，看一下控制台是否有对应的报错信息

**Comment by HaiJeng** [comment]
> 您好，麻烦您在 vscode 的 Help 菜单中点击 Toggle Developer Tools，看一下控制台是否有对应的报错信息

我刚刚使用低版本，提示我登录过期了，之后我选择登出。然后将插件更新到1.8.37当前最新的版本，就可以正常使用了……
无法复刻之前的问题了

**Comment by laggage** [comment]
似乎是因为新的版本似乎无法处理旧的过期的token的问题

**Comment by cnblogs-team** [comment]
@laggage 的确与授权过期有关，详见 #271
