### ISSUE TITLE
支持导出博文为pdf

### ISSUE THREAD

**Issue by laggage** [cnblogs/vscode-cnb#25]
同时支持多选

**Comment by Higurashi-kagome** [comment]
有插件支持将 Markdown 文件转为 PDF，比如 [yzane/vscode\-markdown\-pdf](https://github.com/yzane/vscode-markdown-pdf)，或许将该功能交给这类插件要更好？

**Comment by laggage** [comment]
[vscode-cnb@v0.1.0](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb)已支持
