### ISSUE TITLE
博文下载的时候，报错

### ISSUE THREAD

**Issue by GreyZeng** [cnblogs/vscode-cnb#257]
**问题描述**

博文下载的时候，报错，报错信息为：
![image](https://github.com/cnblogs/vscode-cnb/assets/12782103/e648187d-94a1-4f72-b559-0f19f1d1cb80)

博客下载到本地，名称也变成了【博客名称】+ 几个数字 .md

例如：Java 学习笔记.1343453.md

 - 操作系统: [Windows 11]
 - VSCode版本
 版本: 1.84.2 (system setup)
提交: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
日期: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
 - 博客园扩展版本:v1.8.42

**Comment by cnblogs-team** [comment]
您好，请问您是通过`拉取博文`进行下载的吗？麻烦您退出登录并重新登录试试 

文件名中的数字是 PostId，详见 https://www.cnblogs.com/cmt/p/17865193.html

**Comment by GreyZeng** [comment]
> 您好，请问您是通过`拉取博文`进行下载的吗？麻烦您退出登录并重新登录试试
> 
> 文件名中的数字是 PostId，详见 https://www.cnblogs.com/cmt/p/17865193.html

@cnblogs-team 在随笔分类这里下载的，登录也登录过了

**Comment by cnblogs-team** [comment]
随笔列表中下载有这个问题吗？

试试使用 vscode 的`登出账号`并重新登录，参考  #253

**Comment by cnblogs-team** [comment]
请问在出现这个问题之前使用的是哪个版本？

**Comment by cnblogs-team** [comment]
您好，麻烦您打开 `%userprofile%\.vscode\extensions` 目录，删除所有 `cnblogs.vscode-cnb-` 开头的文件夹，然后重新安装最新版试试

**Comment by GreyZeng** [comment]
> 您好，麻烦您打开 `%userprofile%\.vscode\extensions` 目录，删除所有 `cnblogs.vscode-cnb-` 开头的文件夹，然后重新安装最新版试试

删除了，重新安装，且重新登录，重新设置工作空间了，

但是在【随笔分类】这里，依次点开若干篇博客，工作空间目录里面还是下载下来的博客有几篇还是出现了【博客名称】+ 【几位数字.md】 的那种博客

@cnblogs-team

**Comment by cnblogs-team** [comment]
您好，`【博客名称】+ 【几位数字.md】`就是现在文件名格式，数字是博文ID，有了这个ID可以很方便地与服务端博文关联，详见 https://www.cnblogs.com/cmt/p/17865193.html
