### ISSUE TITLE
如果本地有未上传的更改，从随笔列表中选中该随笔将静默地丢弃这些更改

### ISSUE THREAD

**Issue by dousha** [cnblogs/vscode-cnb#268]
**问题描述**

简单的描述一下你遇到的问题

**复现问题**

复现问题的步骤:

1. 打开本地已关联到博客园的文档
2. 进行编辑
3. 在侧边栏 - Cnblogs console - 随笔列表中选中该文档

**期望的结果**

插件应该提示该文档有未上传的更改，或者将更改传播到新的条目内；至少不应该静默地覆盖本地文档。

**问题截图**

https://github.com/cnblogs/vscode-cnb/assets/4611600/824a4a4f-3754-466a-9d75-66d852b4ae5c

**环境信息:**

 - 操作系统: Windows 10 22H2
 - VSCode版本: 1.84.2
 - 博客园扩展版本: 1.84.5

**Comment by cnblogs-team** [comment]
您好，我们根据您的操作步骤进行了测试并且检查了代码，在默认配置下不会出现这个问题，只有一种情况下会出现这个问题——插件配置中去选了`拉取博文显示确认对话框`并且进行了拉取博文的操作，麻烦您检查一下对应配置

**Comment by dousha** [comment]
> 您好，我们根据您的操作步骤进行了测试并且检查了代码，在默认配置下不会出现这个问题，只有一种情况下会出现这个问题——插件配置中去选了`拉取博文显示确认对话框`并且进行了拉取博文的操作，麻烦您检查一下对应配置

您好，我检查了本地的配置。我已经确认勾选了「拉取博文显示确认对话框」选项，但是该问题仍然存在，如下图所示。

![capture](https://github.com/cnblogs/vscode-cnb/assets/4611600/13e5d03c-82c5-4b93-b873-cd0446a40f5c)

**Comment by cnblogs-team** [comment]
您好，我们会进行改进，改进后无论什么情况下覆盖本地文件时会比较本地文件与服务端文件的内容，如果内容不同，会显示确认对话框

**Comment by cnblogs-team** [comment]
您好，我们已经重构了相关代码，麻烦您更新至 v1.8.50 看看是否还会出现这个问题

**Comment by cnblogs-team** [comment]
先关闭 issue，如果问题依然存在，麻烦您继续反馈
