### ISSUE TITLE
出现扩展无法使用的一种情况

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#271]
下面可能不是扩展的问题，记录在这里，如果其他人有遇到类似情况，可参考解决。

**问题记录**

1. 有一段时间没有用扩展，今天准备发一篇博文
2. 发现使用快捷键上传时提示找不到命令
3. 点击右上角的上传图标，同样提示找不到命令
4. 点击 VSCode 左侧博客园扩展图标，发现“账号中心”、“随笔分类”等都没有展示内容（且未找到重新登录的入口）
5. 重启几次 VSCode/删除本地扩展文件夹/安装旧版本的扩展，未解决问题
6. 打开 VSCode 开发人员工具，发现提示授权过期
7. 点击 VSCode 左下角的用户图标，注销 Cnblogs

	<details>
	<summary>Details</summary>
	
	![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/3f2ccde5-909e-474b-9f85-3e5f2a3ef401)
	
	</details>

8. 重启 VSCode，点击 VSCode 博客园扩展图标，出现登录入口，点击“从浏览器登录”，提示未找到命令
9. 重启 VSCode，再点击登录，成功完成登录

**问题截图**

<details>
<summary>Details</summary>

![image](https://github.com/cnblogs/vscode-cnb/assets/51501079/6545fbd0-9f78-4e28-818f-b5669b3fbbc8)

</details>

**环境信息:**

```
版本: 1.85.0 (user setup)
提交: af28b32d7e553898b2a91af498b1fb666fdebe0c
日期: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

扩展版本：v1.8.47

**Comment by cnblogs-team** [comment]
您好，感谢您提供这个重要线索，我们会尽快修复这个问题

**Comment by cnblogs-dudu** [comment]
是下面的代码引起的
```typescript
if (isAuthSessionExpired(session)) throw Error('授权已过期')
```
在执行 command 时如果遇到异常就会出现 `command not found` 错误提示

**Comment by cnblogs-team** [comment]
您好，已在 `v1.8.49` 中修复，感谢您细致的反馈
