### ISSUE TITLE
路径中带空格时未提取图片

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#272]
**问题描述**

遇到路径中带空格时，未成功提取图片。

**复现问题**

复现问题的步骤:

1. 新建 Markdown
2. Markdown 中加入`res/Nacos 的基本使用之配置管理/img.png`（保证该图片存在）
3. 上传博文（开启图片提取）
4. 发现图片未提取
5. 将`Nacos 的基本使用之配置管理`编码为`Nacos%20%E7%9A%84%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8%E4%B9%8B%E9%85%8D%E7%BD%AE%E7%AE%A1%E7%90%86`并替换
6. 上传博文，成功提取图片

**期望的结果**

正常提取图片

**环境信息:**

```
版本: 1.85.0 (user setup)
提交: af28b32d7e553898b2a91af498b1fb666fdebe0c
日期: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
``` 

扩展版本：v1.8.47

**Comment by cnblogs-team** [comment]
您好，已在 v1.8.48 中修复
