### ISSUE TITLE
无法登陆求助

### ISSUE THREAD

**Issue by lovedva** [cnblogs/vscode-cnb#276]
**问题描述**
登陆之后没有反应，还是停留在登陆界面，尝试再次登陆也没有用。。。
授权登陆和网页登陆都是一样的问题。
![image](https://github.com/cnblogs/vscode-cnb/assets/7524140/2c7e7f9f-530f-48f3-8448-480ba3de4b62)

**Comment by cnblogs-team** [comment]
您好，麻烦您点击 vscode 左下角的账号试试

**Comment by cnblogs-team** [comment]
您好，麻烦您在 vscode 的 Help 菜单中点击 Toggle Developer Tools，看一下控制台是否有对应的报错信息

**Comment by cnblogs-team** [comment]
您好，请问登录问题解决了吗？

**Comment by cnblogs-team** [comment]
先关闭 issue，如果问题未解决，麻烦您继续反馈
