### ISSUE TITLE
[Bug report] 随笔标题中包含特殊字符时拉取失败

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#28]
**问题描述**

随笔标题中包含特殊字符（不能包含在文件名/文件夹名中的字符）时拉取失败。

**复现问题**

复现问题的步骤:
1. 在测试账户中新建并发布一个包含英文双引号（"）的随笔（如 _AutoLISP command 命令中的 "\_\.line" "line" "\-line" 有什么区别_）。
2. 尝试使用扩展将其拉取到本地。
3. 会发现无法正常下载（点击没反应）。

**期望的结果**

扩展能够将包含特殊字符的随笔拉取到本地并正确管理它。

**环境信息:**
 - 操作系统: [Win10]
 - vscode版本 [1.63.2]
 - vscode-cnb版本 [0.0.16]

**Comment by laggage** [comment]
修复了, 升级到 [v0.0.18](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb) 测试体验✌️

**Comment by Higurashi-kagome** [comment]
测试没问题，感谢修复。
