### ISSUE TITLE
[bug] 修改博文设置后图片丢失

### ISSUE THREAD

**Issue by Snoopy1866** [cnblogs/vscode-cnb#284]
**问题描述**

打开已上传的博文md文件，右键->博文设置，修改任何设置后点击确定。前往博客园网页查看博文，发现图片丢失。

**复现问题**

复现问题的步骤:

1. 上传博文
2. 修改博文设置
3. 博文内的图片丢失

**期望的结果**

博文内的图片正常显示。

**问题截图**

如果可能的话, 提供下遇到问题时的截图以便排查

**环境信息:**

 - 操作系统: [Windows 10 专业版 22H2 19045.3803]
 - VSCode版本 [1.85.1]
 - 博客园扩展版本 [1.8.52]

**任何其他有助于排查问题的信息**

扩展设置：
- Auto Extract Images ：“自动提取本地图片”
- Apply Auto Extract Image To Local ：未勾选

**Comment by cnblogs-team** [comment]
您好，为了便于排查问题，麻烦您提供一下出现这个问题的博文地址

**Comment by Snoopy1866** [comment]
https://www.cnblogs.com/snoopy1866/p/17646918.html

**Comment by cnblogs-team** [comment]
您好，我们根据您的操作步骤与帮我内容，未能重现问题，请问出现问题时图片标签被替换成了什么内容？

**Comment by Snoopy1866** [comment]
被替换成了 img

![image](https://github.com/cnblogs/vscode-cnb/assets/45487685/ba82f7e4-c7fe-4964-b633-8d75c32b3dfe)

**Comment by Snoopy1866** [comment]
我尝试重新上传博文，发现图片地址有变化。

step1. 第一次上传博文：https://img2023.cnblogs.com/blog/2482936/202401/2482936-20240107084145823-1272872757.png

step2. 修改博文设置

step3. 第二次上传博文：https://img2023.cnblogs.com/blog/2482936/202401/2482936-20240107084111719-1557214565.png

按 F12 发现 step2 这一步会将图片地址替换为本地路径：

![image](https://github.com/cnblogs/vscode-cnb/assets/45487685/4656d8dd-4adf-449d-8d61-ca7609b407cd)

**Comment by cnblogs-team** [comment]
您好，感谢您的耐心反馈，问题的原因已定位，修改博文设置上传博文时没有进行图片的自动提取

**Comment by cnblogs-team** [comment]
您好，已在 1.8.53 中修复，抱歉，给您带来麻烦了。

**Comment by Snoopy1866** [comment]
感谢，问题已解决。👍
