### ISSUE TITLE
从剪贴板上传图片报错

### ISSUE THREAD

**Issue by GreyZeng** [cnblogs/vscode-cnb#287]
**问题描述**

复制一张图片，然后点击上传图片，从剪切板图片上传，报错

**复现问题**

复现问题的步骤:

1. 复制图片
2. 点击上传图片到博客园
3. 选择剪贴板图片
4. 报错，报错信息如下
![微信截图_20240131155334](https://github.com/cnblogs/vscode-cnb/assets/12782103/acf2f0e5-c318-4e1d-86b3-e4c369459f11)

**环境信息:**

 - 操作系统:windows 11
 - VSCode版本 信息
版本: 1.85.2 (system setup)
提交: 8b3775030ed1a69b13e4f4c628c612102e30a681
日期: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

- 博客园插件版本：v1.8.53

**任何其他有助于排查问题的信息**

在这里填写任何其他有助于排查问题的信息

**Comment by cnblogs-team** [comment]
您好，麻烦您现在再试试

**Comment by GreyZeng** [comment]
> 您好，麻烦您现在再试试

现在已经可以了，是什么问题？

@cnblogs-team

**Comment by cnblogs-team** [comment]
您好，是图片上传服务端的问题
