### ISSUE TITLE
使用插件发布的文章不会显示在自己的博客首页

### ISSUE THREAD

**Issue by imgss** [cnblogs/vscode-cnb#288]
**问题描述**

使用插件发布的文章不会显示在自己的博客首页

**复现问题**

1. 在vscode插件中新建一篇文章
<img width="347" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/20496797/c7ce39d5-af0a-4ef6-bf44-47382ceb7ce0">

2. 简单编辑后点击上传
<img width="410" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/20496797/f6aa6d83-e6dc-462d-9dc4-2736594d2a5c">

3. 点击设置按钮，进入发布页面，最后点击确定
<img width="410" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/20496797/5a38696f-ec4f-42c7-a334-797afd363212">

4. 在管理页面可以看到已发布，但是博客首页没有该文章 https://www.cnblogs.com/imgss
![image](https://github.com/cnblogs/vscode-cnb/assets/20496797/71890b0a-a838-4ba1-931d-4c7e5d1ccd75)

**期望的结果**

[新博文](https://www.cnblogs.com/imgss/p/18045188)显示在[博客首页]( https://www.cnblogs.com/imgss)
**问题截图**

如果可能的话, 提供下遇到问题时的截图以便排查

**环境信息:**

 - 操作系统: [e.g. macOS]
 - VSCode版本 [e.g. 1.00.0]
 - 博客园扩展版本 [e.g. 1.0.0]

**任何其他有助于排查问题的信息**

在这里填写任何其他有助于排查问题的信息

**Comment by cnblogs-team** [comment]
您好，该问题已在 v1.8.54 中修复，抱歉， 给您带来麻烦了。
