### ISSUE TITLE
上传更新博文的Bug

### ISSUE THREAD

**Issue by Wing-summer** [cnblogs/vscode-cnb#29]
比如我修改一个博文，然后我直接点击了上传更新，本地显示已保存，但博文却没有更新。经检查我再重复操作就可以更新，由于不会写`vscode`的插件，也没看源码，猜测是由于保存本地操作在上传更新之后导致该问题，这个小`Bug`望修复。

**Comment by laggage** [comment]
67ea3f43be62aacb87921076c82d98521838bb26

**Comment by laggage** [comment]
已修
