### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by FelixYu2021202** [cnblogs/vscode-cnb#292]
我试过重装该插件，但它总是显示 `There is no data provider registered that can provide view data.`
<img width="381" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/53996080/920331fd-80bf-4e3d-9d1f-4f7387b0d9e0">

**Comment by cnblogs-team** [comment]
您好，请问您用的是什么操作系统？vscode 用的是哪个版本？

**Comment by FelixYu2021202** [comment]
mac, vscode insider 1.90.0

**Comment by cnblogs-team** [comment]
您好，麻烦您试试点击 vscode 左下角的账号（Accounts）按钮对扩展进行授权

**Comment by FelixYu2021202** [comment]
呃，我这边是这样的，貌似找不到这个插件：
<img width="1086" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/53996080/78241812-dd40-4ca7-8063-76c9f6bdea6a">

**Comment by cnblogs-team** [comment]
您好，麻烦您在 Finder 中进入 `~/.vscode/extensions` 路径，删除 `cnblogs.vscode` 开头的文件夹，然后重新安装插件试试

**Comment by FelixYu2021202** [comment]
呃，仍然无效

**Comment by FelixYu2021202** [comment]
顺带提一下，这个按钮按了没效果：
<img width="279" alt="image" src="https://github.com/cnblogs/vscode-cnb/assets/53996080/ec81da4a-f50f-4edf-bcca-69185866db34">

**Comment by 463f** [comment]
同样的问题，vscode（Windows）更新到1.9.0后也出现无法登录的情况

**Comment by zpy1160390580** [comment]
是的，我vscode更新到1.90无法使用了，该怎么修改一下呢？

**Comment by zpy1160390580** [comment]
按上述的这些方法都不可行

**Comment by zpy1160390580** [comment]
是的，我vscode更新到1.90无法使用了，该怎么修改一下呢？按上述的这些方法都不可行

![image](https://github.com/cnblogs/vscode-cnb/assets/101700134/756fa1f9-09ee-433e-a05d-80d19eb4fcae)

**Comment by 463f** [comment]
> 同样的问题，vscode（Windows）更新到1.9.0后也出现无法登录的情况

@cnblogs-team 在Ubuntu第一次安装 vscode(1.90)、只安装博客园插件，仍出现该问题，显示 `There is no data provider registered that can provide view data.`

**Comment by cnblogs-team** [comment]
您好，这个问题与 vscode 1.90 的变更有关，问题还在排查中

**Comment by cnblogs-team** [comment]
您好，该问题已在 1.8.55 中解决
