### ISSUE TITLE
There is no data provider registered that can provide view data.

### ISSUE THREAD

**Issue by Paramecium1023** [cnblogs/vscode-cnb#293]
**问题描述**

简单的描述一下你遇到的问题

**复现问题**

复现问题的步骤:

1. 在某个地方 ...
2. 进行了什么操作 ...
3. ...

**期望的结果**

你期望的结果

**问题截图**
![image](https://github.com/cnblogs/vscode-cnb/assets/115788051/90227b7c-779e-4555-b8fe-f84530f81141)

如果可能的话, 提供下遇到问题时的截图以便排查

**环境信息:**

 - 操作系统: [e.g. macOS]
 - VSCode版本 [e.g. 1.00.0]
 - 博客园扩展版本 [e.g. 1.0.0]

**任何其他有助于排查问题的信息**

在这里填写任何其他有助于排查问题的信息

**Comment by qinguoming** [comment]
![image](https://github.com/cnblogs/vscode-cnb/assets/87171717/6fbd914f-12b7-400f-92d7-553308218f2c)
操作系统: [windows 10]
VSCode版本 [1.90]
博客园扩展版本 [1.8.54]

**Comment by cnblogs-team** [comment]
您好，这个问题与 vscode 1.90 的变更有关，问题还在排查中

**Comment by cnblogs-team** [comment]
您好，该问题已在 1.8.55 中解决
