### ISSUE TITLE
没有可提供视图数据的已注册数据提供程序

### ISSUE THREAD

**Issue by HeimuCliff** [cnblogs/vscode-cnb#294]
**问题描述**

简单的描述一下你遇到的问题
安装完插件之后 没有可提供视图数据的已注册数据提供程序 没有显示登录的logo

**Comment by cnblogs-team** [comment]
您好，这个问题与 vscode 1.90 的变更有关，问题还在排查中

**Comment by cnblogs-team** [comment]
您好，该问题已在 1.8.55 中解决
