### ISSUE TITLE
建议博文设置提供一个面板操作

### ISSUE THREAD

**Issue by Wing-summer** [cnblogs/vscode-cnb#30]
希望能把博文设置搬到界面当中，而不是点击上传更新再做，因为有很多操作是没有的，如果不小心点错了还需到网页端后台进行修改，要么直接不上传还得重来。标签建议提供下拉列表的形式提供，因为我在后台使用的标签就那几个。

**Comment by laggage** [comment]
[v0.0.2](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb) 中已实现
