### ISSUE TITLE
博客标题导致的插件无法打开博文

### ISSUE THREAD

**Issue by XuYueming520** [cnblogs/vscode-cnb#300]
**问题描述**

windows 环境，当博客标题中含有 `#` 时，拉取随笔后，通过插件的“随笔列表”中无法正常打开文件，但是可以手动打开编辑。

**复现问题**

复现问题的步骤:

拉取一篇标题中含有 `#` 的随笔，尝试打开，提示错误。

**期望的结果**

正常打开随笔 markdown 编辑界面。

**问题提示**

> 博文关联的本地文件不存在，postId: 18016461，path: c:\Users\Administrator\Documents\Cnblogs\洛谷 P9912 [COCI 20232024 

即 `#` 后的文本丢失，无法找到文件。

**环境信息:**

- Windows版本 windows7
 - VSCode版本 1.88.1
 - 博客园扩展版本 v1.8.55

**Comment by cnblogs-dudu** [comment]
您好，已在 v1.8.58 中修复，现在会把文件名的英文 `#` 替换全角 `＃`
