### ISSUE TITLE
[Bug] 分类的右键菜单

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#33]
**问题描述**

分类的右键菜单中包含不合适的选项，且“在线查看博文”和“删除随笔(支持多选)”不能够正常工作。

**复现问题**

复现问题的步骤:

1. 展开“分类列表”；
2. 右键单击某一分类；
3. 可以看到如下右键菜单：
	  <details>
	  <summary>Details</summary>
	  
	  ![image](https://user-images.githubusercontent.com/51501079/152153265-a9040089-6a50-48bd-a457-faf8ba90cd16.png)
	  
	  </details>
4. 单击“删除随笔(支持多选)”会出现如下弹窗（注意到其中的“工具”为分类名，“Ther”为“工具”下的某一篇博文的标题）：
	  <details>
	  <summary>Details</summary>
	  
	  ![image](https://user-images.githubusercontent.com/51501079/152154036-728fed84-8ff4-4250-9ef6-8d0d3992a1bd.png)
	  
	  </details>
5. 单击“在线查看博文”无反应。

**期望的结果**

1. 单击“在线查看博文”应该进入相应分类页面（https:\/\/i.cnblogs.com/posts?cateId=***），而实际上单击无反应；
2. 菜单中不应该包含“修改博文设置”和“重命名博文”；
3. 单击“删除随笔(支持多选)”应该是弹出一个包含分类下对应文章的复选框列表，以支持**多选**删除文章。

**环境信息**

操作系统：[Win10]

vscode 版本 [1.63.2]

vscode-cnb 版本 [0.0.16]

**Comment by laggage** [comment]
❤️感谢反馈，修复了，升级到0.0.17即可
