### ISSUE TITLE
博文为 HTML 类型

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#35]
**问题描述**

注意到有些博文显示为 HTML 类型，而大多数博文是 Markdown 格式。HTML 不那么好编写内容，是否能够都将博文以 Markdown 格式管理？

**环境信息:**
 - 操作系统: [Win10]
 - vscode版本 [1.64.2]
 - vscode-cnb版本 [0.0.17]

**Comment by laggage** [comment]
如果你在[博客后台](https://i.cnblogs.com/posts)使用的是tinymce或者tinymce5这种富文本编辑器编辑的博文，那么在vscode中打开这篇博文时后缀就是html的

**Comment by Higurashi-kagome** [comment]
哦，谢谢。
