### ISSUE TITLE
允许通过命令面板调用`保存到博客园`命令

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#37]
**问题描述**

使用 VSCode 右上角的“保存到博客园”按钮能够正常将博文发布到博客园。后来想通过命令面板（Ctrl+Shift+P）发布，发现命令面板中没有相关的命令：

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/155717102-11697c02-6c24-404a-9bff-f003eef80b12.gif)

</details>

转到快捷键绑定发现有相关命令，于是绑定了快捷键（没有快捷键冲突）想通过快捷键发布，但发现下图中红框内的按键都不能够正常生效（按下无反应）：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/155716714-eba8906e-f59a-417e-ad12-5adbfd307836.png)

</details>

其中绿色框内的快捷键都能够正常唤起命令。

**期望的结果**

命令面板中提供发布博文的命令、发布博文的命令能够正常绑定快捷键。

**环境信息**
 
- 操作系统 [Win10]
 - vscode版本 [1.64.2]
 - vscode-cnb版本 [0.0.18]

**Comment by laggage** [comment]
目前是故意不让通过命令面板调用`保存到博客园`命令，不过考虑到快捷键的需求，可以放出这个命令允许通过命令面板调用

**Comment by laggage** [comment]
[vscode-cnb@v0.1.0](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb)已支持
