### ISSUE TITLE
文件名标签的上传图片按钮无效

### ISSUE THREAD

**Issue by Wing-summer** [cnblogs/vscode-cnb#43]
**问题描述**
通过点击该按钮没有任何反应，但右键菜单有效，版本：0.2.0
![image](https://user-images.githubusercontent.com/59953528/161064842-524056a0-0749-4b04-a6ed-aa85b9831182.png)

**Comment by laggage** [comment]
感谢使用和反馈，[v0.2.1](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb)中已修复
