### ISSUE TITLE
允许通过命令面板调用`在线查看博文`命令

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#47]
发布或修改博文的时候，通常会想要在网页上检查一下，所以`在线查看博文`是一种比较常用的操作。另外，在修改发布有一段时间的文章的时候，想要预览修改后的内容，需要在多条甚至多页博文中找到对应的博文，然后右键点击来跳转到浏览器，比较麻烦，建议支持命令行调用，方便绑定快捷键。

**Comment by laggage** [comment]
已发布 [v1.2.0](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb)
