### ISSUE TITLE
在 deepin下上传博文加载不出来

### ISSUE THREAD

**Issue by Wing-summer** [cnblogs/vscode-cnb#53]
在 Deepin 系统上进行上传新建博文，博文设置一直会卡在数据加载中，望修复。

系统：Deepin
触发：新建博文
现象：
![image](https://user-images.githubusercontent.com/59953528/167534179-c75e1e6c-c701-4571-af15-8b9cfe631310.png)

**Comment by laggage** [comment]
使用的deepin和vscode的版本是多少啊？这边在`deepin 20.5`上用`vscode@1.66.2`测试是可以的

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/38829279/168032930-32e1f486-f09c-49ce-9021-76fabd884d9d.png">

**Comment by Wing-summer** [comment]
vscode 版本:
![image](https://user-images.githubusercontent.com/59953528/168040557-e952fb45-dbd6-41e8-ac17-8f2fd95a158c.png)

Deepin:
![image](https://user-images.githubusercontent.com/59953528/168040721-ec0284ad-9b50-4859-9ec9-907ad4d47cc1.png)

**Comment by laggage** [comment]
现在应该好了，可以用最新版[1.2.1](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb&ssr=false#overview)试试看. 是vscode1.67.x版本`await WebView.PostMessage`一直不返回导致的

**Comment by Wing-summer** [comment]
经测试已通过，正常使用，感谢！
