### ISSUE TITLE
是否可以支持 jetbrains

### ISSUE THREAD

**Issue by XiaoHuiHuiT** [cnblogs/vscode-cnb#58]
- 因本人是基于 jetbrains 下的 idea 进行创作
- 如果可以支持 jetbrains 那就更好了

**Comment by laggage** [comment]
印象中jetbrains好像没有单独的markdown ide啊

**Comment by BNTang** [comment]
这个是需要一个 markdown 的ide 才可以吗

**Comment by BNTang** [comment]
> 印象中jetbrains好像没有单独的markdown ide啊

这个是需要一个 markdown 的ide 才可以吗

**Comment by Higurashi-kagome** [comment]
就我自己的感受来说，在 JetBrains 上写 MarkDown 并不怎么方便。JetBrains 比较重，而 VSCode 比较轻，且扩展很丰富（虽然也的确有点乱）。

**Comment by BNTang** [comment]
> 就我自己的感受来说，在 IDEA 上写 MarkDown 并不怎么方便。IDEA 比较重，而 VSCode 比较轻，且扩展很丰富（虽然也的确有点乱）。

嗯，算了，我觉得在VS Code 也是挺方便的
