### ISSUE TITLE
支持自动上传本地图片

### ISSUE THREAD

**Issue by Higurashi-kagome** [cnblogs/vscode-cnb#63]
### ui上的哪部分与此新功能有关?

侧边栏文件浏览右键上下文菜单, 其他

### 新功能描述

有时候，会在草稿中引用本地图片。比如有时候想要转载一篇博文，会复制粘贴博文内容，并将博文中的图片下载到本地。这时候，想要将博文转载到博客园，需要将本地图片一张张上传，或许可以提供一个快捷的功能？

### [选填]建议的解决方案

可以在发布草稿时，检测草稿中的图片链接是否指向本地，如果是，则将图片上传，并将本地图片的链接替换为上传后的博客园图片链接：

```
![img](res/up-2e6117a346fa3306c506c5bc469e8f8b27b.png)
```

\>\>\>\>

```
![img](https://img2022.cnblogs.com/blog/**/*-144666955.png)
```

或者——如果上面不好实现的话——可以在图片上提供一个右键菜单，用来将其上传到博客园：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/182156503-a75ed2ed-72ec-41db-addd-8e277f04d48a.png)

</details>

又或者，可以在打开图片时，在右上角加一个上传按钮：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/182156723-5c44684c-a649-4ec4-9e4d-6e7f8dfa06c2.png)

</details>

**Comment by laggage** [comment]
[v1.3.0](https://marketplace.visualstudio.com/items?itemName=cnblogs.vscode-cnb#%E6%8F%90%E5%8F%96%E5%9B%BE%E7%89%87)中已实现提取图片
