### ISSUE TITLE
允许一次性下载全部博文到本地

### ISSUE THREAD

**Issue by laggage** [cnblogs/vscode-cnb#64]
### ui上的哪部分与此新功能有关?

侧边栏控制台随笔列表

### 新功能描述

侧边栏控制台随笔列表提供下载全部博文到本地的操作，点击后打开配置面板，允许配置本地有同名文件时的处理方式、博文分类的处理方式等

**Comment by cnblogs-team** [comment]
您好，现已实现，目前至针对VIP会员开放这个功能。
