### ISSUE TITLE
有关随笔分类和搜索的建议

### ISSUE THREAD

**Issue by cnblogs-team** [cnblogs/vscode-cnb#66]
来自评论：https://www.cnblogs.com/cmt/p/15768371.html#5100817

希望插件添加如下功能:

“分类列表”中实现点击列表展开列表中的文章，便于文章查找。
“随笔列表”中实现搜索功能，根据文章名和文章内容搜索出需要的文章。其实有个办法不实现都可以，就是需要把所有文章在列表中全部显示，不采用分页的形式，这样可以使用vscode的搜索功能，搜索文章名。
写博客本来就是为了后面查看，能快速找到需要的文章，才方便后续查看。

**Comment by laggage** [comment]
[v1.4.0](https://github.com/cnblogs/vscode-cnb/releases/tag/v1.4.0) 中已支持
