### ISSUE TITLE
剪贴板中没有找到图片

### ISSUE THREAD

**Issue by yujianke100** [cnblogs/vscode-cnb#71]
**问题描述**
简单的描述一下你遇到的问题.

截图后选择“上传剪切板图片到博客园”时，显示“剪贴板中没有找到图片”
**复现问题**
复现问题的步骤:
1. 截图
2. 右键“上传剪切板图片到博客园”
3. 提示显示“剪贴板中没有找到图片”

**期望的结果**
告知解决问题的方式

**环境信息:**
 - 操作系统: windows10 LTSC
 - vscode版本 1.71.2
 - vscode-cnb版本1.3.1

**任何其他有助于排查问题的信息**
我尝试了其他插件，也都无法识别剪切板中的图片，因此我怀疑是vscode的设置问题或版本问题。不过在设置了”Editor › Experimental › Paste Actions: Enabled“后任然无效。

**Comment by laggage** [comment]
用的什么软件截得图啊？

**Comment by laggage** [comment]
在github issue中`ctrl + v` 粘贴图片试试能上传到github吗？不能的话应该是图片没复制成功吧

**Comment by yujianke100** [comment]
尝试过钉钉和系统自带的截图，且在`win+v`剪切板里能看到截图，在画图软件中可以正常粘贴。以下是在这里`ctrl+v`的结果：
![image](https://user-images.githubusercontent.com/35999482/191895775-aa8f165b-d027-4e22-a9cc-1d7d8c75c8ee.png)

**Comment by laggage** [comment]
我不清楚你具体是如何操作的，我这边用自带的截图软件测试可以正常上传

测试步骤：
1. 键盘快捷键`win+shift+s`唤起自带的截图程序
2. vscode编辑器右键选择上传剪贴板图片

![2022-09-23 13 29 18](https://user-images.githubusercontent.com/38829279/191897435-4623dc99-eaf1-45f5-8e5d-fd501a1744f7.gif)

建议用管理员身份打开vscode试试；

如果还是不行，vscode中`ctrl+shift+p`唤起命令面板，找到 `Developer: Toggle Developer Tools` 命令，点击可以打开 开发者工具，看看控制台有没有相关的错误

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/38829279/191898151-b6bc901d-2e70-4e5f-ae4e-6296694a9c93.png">

**Comment by yujianke100** [comment]
已全部尝试，控制台没有任何反映。既然不是插件问题，我这边关闭了吧。可能是办公的电脑上有什么策略导致的
