### ISSUE TITLE
本地md文件删除之后，无法关联更新

### ISSUE THREAD

**Issue by hongzhe-github** [cnblogs/vscode-cnb#74]
**问题描述**
本地md文件删除之后，无法关联更新

**复现问题**
复现问题的步骤:
1. 删除本地文件后
2. 点击鼠标右键命令面板关联到博客
3. 搜索不出来博客
4. 尝试过重新登录，和设置工作路径

**期望的结果**
关联成功

**环境信息:**
 - windwos11: [e.g. iOS]
 - 版本: 1.70.1 (user setup)
  提交: 6d9b74a70ca9c7733b29f0456fd8195364076dda
  日期: 2022-08-10T06:08:33.642Z
  Electron: 18.3.5
  Chromium: 100.0.4896.160
  Node.js: 16.13.2
  V8: 10.0.139.17-electron.0
  OS: Windows_NT x64 10.0.22000
  沙盒化: undefined
 - vscode-cnb版本 [v1.3.2]

**Comment by laggage** [comment]
> 搜索不出来博客

<img width="667" alt="image" src="https://user-images.githubusercontent.com/38829279/196471318-6a7ca564-a0c4-4ac0-b7a3-87073f789b9d.png">
是在这个页面搜不到博文吗？换个关键词试试？

**Comment by hongzhe-github** [comment]
是的，是在这个界面搜索不到，最近的随笔可以搜索到，但是现在我删除了随笔，现在都搜索不到了。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月18日 23:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [cnblogs/vscode-cnb] 本地md文件删除之后，无法关联更新 (Issue #74) |

搜索不出来博客

是在这个页面搜不到博文吗？换个关键词试试？

**Comment by laggage** [comment]
> 最近的随笔

指的是插件控制台的随笔列表吗？

我这边尝试了删除本地文件关联的博客园随笔，然后再调用`博客园关联博文`命令，第一次会在右下角出现错误提示`博文不存在`，然后再次调用`博客园关联博文`命令，可以正常搜索博客园随笔

<img width="471" alt="image" src="https://user-images.githubusercontent.com/38829279/197096202-4fe5605e-0244-4c8f-9cd7-55dfc568fadf.png">

<img width="608" alt="image" src="https://user-images.githubusercontent.com/38829279/197096221-ab5c218f-497e-4def-860e-fa3b921bfc62.png">

**Comment by hongzhe-github** [comment]
好的，我会再次尝试，如果还有问题，我讲具体错误情况发送至邮箱📭，感谢！



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月21日 10:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [cnblogs/vscode-cnb] 本地md文件删除之后，无法关联更新 (Issue #74) |

最近的随笔

指的是插件控制台的随笔列表吗？

我这边尝试了删除本地文件关联的博客园随笔，然后再调用博客园关联博文命令，第一次会在右下角出现错误提示博文不存在，然后再次调用博客园关联博文命令，可以正常搜索博客园随笔
