### ISSUE TITLE
支持提取 vscode foam 的 wikilink 形式的资源/图片

### ISSUE THREAD

**Issue by figuremout** [cnblogs/vscode-cnb#83]
### ui上的哪部分与此新功能有关?

markdown编辑器右键上下文菜单

### 新功能描述

目前只能提取`![]()`形式的图片，但是也有很多人在 vscode 用 foam 插件写双链笔记，使用`![[wikilink]]`形式。

### [选填]建议的解决方案

vscode foam 插件提供了 wikilink 兼容其他 markdown 工具的方式，比如在文档中写入`![[PIO.png]]`并保存后，会自动在笔记末尾生成并维护一个 link references：
```md
[//begin]: # "Autogenerated link references for markdown compatibility"
[PIO.png]: ../_resources/PIO.png "PIO.png"
[//end]: # "Autogenerated link references"
```
保存到博客园时只需要找出文档中所有`[[wikilink]]`形式的链接，再对照末尾的 link references 找到相对路径上传图片即可。

**Comment by cnblogs-dudu** [comment]
提取 wikilink 图片的 js 正则是 `/!\[(\[.+?\])\][\s\S]+?\1:\s*(.*?)\s+/g`，但现在提取图片部分是用 Rust 实现的，而 Rust 正则不支持 backreference ，需要重构 [find-img-link.ts](https://github.com/cnblogs/vscode-cnb/blob/v1.8.44/src/service/extract-img/find-img-link.ts) 与 [extract-img.ts](https://github.com/cnblogs/vscode-cnb/blob/v1.8.44/src/cmd/extract-img.ts) 移除 Rust 实现的部分

**Comment by cnblogs-team** [comment]
您好，抱歉，让您等太久了，已在 v1.8.46 中实现，如果遇到不能提取的情况，麻烦您向我们反馈
