### ISSUE TITLE
将随笔关联数据保存在本地json文件内

### ISSUE THREAD

**Issue by figuremout** [cnblogs/vscode-cnb#84]
### 新功能描述

我个人倾向于在本地保存、编辑和管理所有笔记，然后选择部分笔记上传博客园。
在使用中有以下两种情况：
1. 将本地笔记文件夹移动位置后，随笔关联记录的绝对路径并不会更新，需要手动重新关联
2. 如果需要更换电脑，将笔记的文件夹copy到新电脑后再用vscode打开，所有随笔都需要重新关联

如果笔记量大的话，手动重新关联可能既繁琐又不准确。

### [选填]建议的解决方案

1. 关联的本地路径采用相对路径（相对于`cnblogsClientForVSCode.workspace`？）
2. 使用json存储关联（json存储位置可配置）

如有以下目录结构：
```
|- ~/Documents/Notes
    |- other notes
    |- publish
        |- .vscode/
            |- vscode-cnb.json
        |- dir/
            |- 1.md
        |- 2.md
```

settings.json 中配置：
```json
{
  "cnblogsClientForVSCode.workspace": "~/Documents/Notes/publish",
  "cnblogsClientForVSCode.relations": ".vscode/vscode-cnb.json" // 关联存储位置的相对路径
}
```
则关联数据的存取通过`publish/.vscode/vscode-cnb.json`：
```json
{
  "relations": [
    {"local": "dir/1.md", "web": "https://www.cnblogs.com/xxx/p/xxx.html"},
    {"local": "2.md", "web": "https://www.cnblogs.com/xxx/p/xxx.html"},
  ]
}
```

这样只需要`Notes/`文件夹在手，不怕到处移动丢失关联数据

**Comment by cnblogs-dudu** [comment]
现在采用一个变通且更彻底的解决方法，在文件名中包含 postId 并通过 postId 与服务端博文进行关联，从 [v1.8.38](https://github.com/cnblogs/vscode-cnb/releases/tag/v1.8.38) 开始拉取博文时会生成的文件名中包含 postId，比如 `会员救园.17520031.md`。

这样无论在哪个路径下，无论在哪台电脑上，只要文件在手，在`上传到博客园`时，如果没有关联，点击`关联已有博文并上传`即可，会基于文件名中的 postId 自动完成关联，拉取博文也是一样。

欢迎更新至 [v1.8.41](https://github.com/cnblogs/vscode-cnb/releases/tag/v1.8.41) 体验。
