### ISSUE TITLE
这啥阴间快捷键？

### ISSUE THREAD

**Issue by YOYO-UIAT** [cnblogs/vscode-cnb#90]
```
{
  "key": "ctrl+s ctrl+c",
  "command": "vscode-cnb.ing.publish",
  "when": "vscode-cnb.isAuthorized"
}
```

这个”发闪存“的快捷键与”保存“的 Ctrl-S 冲突了，导致 Ctrl-S 无法使用。

**Comment by laggage** [comment]
对此深感抱歉，[v1.5.1](https://github.com/cnblogs/vscode-cnb/releases/tag/v1.5.1)版本中已移除这个快捷键, 望谅解

**Comment by YOYO-UIAT** [comment]
> 对此深感抱歉，[v1.5.1](https://github.com/cnblogs/vscode-cnb/releases/tag/v1.5.1)版本中已移除这个快捷键, 望谅解

没事，感谢你的快速修复
