### ISSUE TITLE
[BUG] 对分类名中的特殊字符没有进行转义

### ISSUE THREAD

**Issue by Winterreisender** [cnblogs/vscode-cnb#97]
**问题描述**
分类中含有`/`的时候会创建完整的路径而不是一个文件夹。不清楚这是一个BUG还是Feature

**复现问题**
复现问题的大致步骤:
1. 在网页端创建一个名为`C/C++`的分类,里面写一篇博文,标题为`Example`
2. 在客户端下载这篇博文
3. 发现这篇博文的存储路径是`Workspace/C/C++/Example.md`

**期望的结果**
对分类名中的特殊字符进行转义,比如`Workspace/C_C++/Example.md`或`Workspace/C%2FC%2B%2B/Example.md`

**问题截图**
-

**环境信息:**
 - 操作系统: Windows 10 22H2
 - vscode版本 1.73.1
 - vscode-cnb版本 v1.6.0

**Comment by laggage** [comment]
这是个bug

**Comment by laggage** [comment]
[v1.6.1](https://github.com/cnblogs/vscode-cnb/releases/tag/v1.6.1) 中会进行转义了，`/` 会转义成`_`, 其余非法字符会直接被移除
