### ISSUE TITLE
增加 YAML front matter 的解析

### ISSUE THREAD

**Issue by Teemwu** [cnblogs/vscode-cnb#98]
### ui上的哪部分与此新功能有关?

markdown编辑器工具栏

### 新功能描述

上传已有文章并新建文章时 YAML front matter 的前置信息并没有去除，直接显示出来了，而 VSCode 的 markdown 预览会自动去除这一部分的，如下图：

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/16522288/207211962-010aa968-9c4c-436f-9078-2d574f92845e.png">

而博客园中显示如下：

<img width="856" alt="image" src="https://user-images.githubusercontent.com/16522288/207212683-59f5cf51-6173-4a12-9b18-9a7982c08e17.png">

### [选填]建议的解决方案

1. 过滤掉文章前置信息
2. 解析前置信息，提取读取到的字段，在新建文章时让用户来手动对应分类、标签等信息
3. 开放预处理接口或配置，让用户自己处理 markdown 内容

**Comment by laggage** [comment]
> 而 VSCode 的 markdown 预览会自动去除这一部分的

这是期望的结果吗？

**Comment by Teemwu** [comment]
@laggage 对的，正常情况下，不应该显示这一块内容。

**Comment by zwyyy456** [comment]
同求，cnblogs 显示的博客内容不应当包含 YAML front matter 中的内容，以及是否可以解析 catogories 以及tags 中的信息，从而在博客园创建对应分类和标签的博文呢？

**Comment by laggage** [comment]
frontmatter部分可以智能提示支持的字段会更好
